# Generated by Django 2.1.1 on 2018-09-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneDayInWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work', models.DateTimeField()),
                ('end_work', models.DateTimeField()),
                ('date_work', models.DateField()),
                ('sum_day', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['date_work'],
            },
        ),
    ]
