# Generated by Django 2.1.1 on 2018-09-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OneDayInWork',
            new_name='DaysAtWork',
        ),
    ]
