# Generated by Django 2.1.1 on 2018-09-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20180930_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysatwork',
            name='end_work',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='daysatwork',
            name='start_work',
            field=models.TimeField(),
        ),
    ]
