# Generated by Django 2.1.1 on 2018-10-11 10:53

from django.conf import settings
from django.db import migrations, models
import salary.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0003_auto_20180930_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysatwork',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=models.SET(salary.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
